---
title: About AdonisJs
permalink: about
category: Preface
---

= Sobre o AdonisJs

toc::[]

AdonisJS é um Framework MVC Node.js que funciona em todos os principais sistemas operacionais. Ele oferece um ecosistema estável para escrever aplicações web do lado do servidor, então vocẽ pode focar nas necessidades do negócio ao invés de ficar escolhendo qual pacote escolher ou não.

AdonisJs favorece o desenvolvedor curtir com uma consistente e expressiva API para construir aplicações web fullstack ou micro API.

== Iniciando

Não há pré-requisitos complicados para usar AdonisJs, mas ter um entendimento convencional de Javascript, Programação assíncrona e Node.js é muito útil.

Também, se você é novo no Javascript ou não é familiar com seu recente progresso no ES6, nós recomendamos assistir link:https://goo.gl/ox3uSc[Wes Bos's ES6 course, window="_blank"].

Finalmente, certifique de ler através do nosso guia de link:installation[instalação], especialmente se essa é sua primeira vez usando AdonisJs.

== Providers
AdonisJs é um framework modular que consiste de multiplos provedores de serviços, os elementos básicos das aplicações AdonisJs. 

In theory, they are like any other npm module with some code on top to work smoothly with AdonisJs applications (for example, link:https://github.com/adonisjs/adonis-bodyparser[BodyParser] to parse the HTTP request body, or link:https://github.com/adonisjs/adonis-lucid[Lucid] which is a SQL ORM).

== FAQ's
Below is the list of frequently asked questions. If you think a common question is missing from the list, please create an issue link:https://github.com/adonisjs/docs[here].

[ol-spaced]
1. *How is AdonisJs different to Express or Koa?*
+
Express and Koa are routing libraries with a thin layer of middleware on top. They are great for several use cases but fall apart when projects start to grow.
+
Since your projects have their own standards and conventions, it may become harder to hire developers to work on them. As AdonisJs follows a set of standardized conventions, it should be easier to hire someone to work on existing AdonisJs apps.

2. *Is AdonisJs for monolithic apps?*
+
No. The AdonisJs Framework is a combination of multiple packages that gracefully integrate with the rest of your application.
+
The framework provides a robust link:ioc-container[dependency injection] layer leveraged by all official and 3rd party packages to offer functionality without manually wiring up each part of your app.
